using System.IO;
using Newtonsoft.Json.Linq;
using UnityEditor;
using UnityEngine;

namespace McpBridge.Handlers
{
    public static class CodegenHandler
    {
        public static UnityResponse WriteFile(UnityCommand cmd)
        {
            string relativePath = cmd.Payload["path"]?.Value<string>();
            string content = cmd.Payload["content"]?.Value<string>();

            if (string.IsNullOrEmpty(relativePath))
                return UnityResponse.Fail(cmd.Id, "Missing 'path' in write_file payload");
            if (content == null)
                return UnityResponse.Fail(cmd.Id, "Missing 'content' in write_file payload");

            string fullPath = Path.Combine(Application.dataPath, relativePath);
            string dir = Path.GetDirectoryName(fullPath);
            if (!Directory.Exists(dir)) Directory.CreateDirectory(dir);

            File.WriteAllText(fullPath, content);

            return UnityResponse.Success(cmd.Id, new JObject
            {
                ["file_written"] = fullPath,
                ["bytes"] = content.Length
            });
        }

        public static UnityResponse AssetRefresh(UnityCommand cmd)
        {
            AssetDatabase.Refresh();
            return UnityResponse.Success(cmd.Id, new JObject { ["refreshed"] = true });
        }

        public static UnityResponse GenerateGameManager(UnityCommand cmd)
        {
            return UnityResponse.Success(cmd.Id, new JObject
            {
                ["note"] = "GameManager.cs is generated by the Rust codegen module via write_file + asset_refresh."
            });
        }

        public static UnityResponse GenerateStationScripts(UnityCommand cmd)
        {
            return UnityResponse.Success(cmd.Id, new JObject
            {
                ["note"] = "Station scripts are generated by the Rust codegen module via write_file + asset_refresh."
            });
        }

        public static UnityResponse GenerateScriptables(UnityCommand cmd)
        {
            return UnityResponse.Success(cmd.Id, new JObject
            {
                ["note"] = "ScriptableObject scripts are generated by the Rust codegen module via write_file + asset_refresh."
            });
        }

        public static UnityResponse GenerateOrderSystem(UnityCommand cmd)
        {
            return UnityResponse.Success(cmd.Id, new JObject
            {
                ["note"] = "OrderManager + OrderUI are generated by the Rust codegen module via write_file + asset_refresh."
            });
        }

        public static UnityResponse GeneratePlayerController(UnityCommand cmd)
        {
            return UnityResponse.Success(cmd.Id, new JObject
            {
                ["note"] = "PlayerController.cs is generated by the Rust codegen module via write_file + asset_refresh."
            });
        }
    }
}
